# Generated by Django 6.0.4 on 2026-04-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sale_stockreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_quantity',
            field=models.PositiveIntegerField(default=5, verbose_name='Минимальный остаток'),
        ),
    ]
