# Generated by Django 6.0.4 on 2026-04-09 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_minimum_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date'], 'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='stockreceipt',
            options={'ordering': ['-receipt_date'], 'verbose_name': 'Поступление', 'verbose_name_plural': 'Поступления'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Минимальный остаток'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='receipt_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='supplier',
            field=models.CharField(max_length=200, verbose_name='Поставщик'),
        ),
    ]
