# Generated by Django 6.0.4 on 2026-04-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplier_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], default='Женский', max_length=20, verbose_name='Пол'),
        ),
    ]
