# Generated by Django 6.0.4 on 2026-04-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_saleorder_saleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поступление (накладная)',
                'verbose_name_plural': 'Поступления (накладные)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Товар')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.receiptorder', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'Позиция поступления',
                'verbose_name_plural': 'Позиции поступления',
            },
        ),
    ]
