# Generated by Django 6.0.4 on 2026-04-22 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_receiptorder_receiptitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Журнал действий', 'verbose_name_plural': 'Журнал действий'},
        ),
        migrations.AlterModelOptions(
            name='receiptorder',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Накладная поступления', 'verbose_name_plural': 'Накладные поступления'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date', '-id'], 'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Чек продажи', 'verbose_name_plural': 'Чеки продаж'},
        ),
        migrations.AlterModelOptions(
            name='stockreceipt',
            options={'ordering': ['-receipt_date', '-id'], 'verbose_name': 'Поступление', 'verbose_name_plural': 'Поступления'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='comment',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=100, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущее количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=10, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='receiptorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.saleorder', verbose_name='Чек'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
